export default {
    LOAD_SCORES_REQUEST: 'LOAD_SCORES_REQUEST',
    LOAD_SCORES_SUCCESS: 'LOAD_SCORES_SUCCESS',
    LOAD_SCORES_FAILED: 'LOAD_SCORES_FAILED',
    ADD_SCORE_SUCCESS: 'ADD_SCORE_SUCCESS',
    ADD_SCORE_REQUEST: 'ADD_SCORE_REQUEST',
    ADD_SCORE_FAILED: 'ADD_SCORE_FAILED',
    LOAD_SCORE_REQUEST: 'LOAD_SCORE_REQUEST',
    LOAD_SCORE_SUCCESS: 'LOAD_SCORE_SUCCESS',
    GET_SCORE_REQUEST: 'GET_SCORE_REQUEST',
    GET_SCORE_SUCCESS: 'GET_SCORE_SUCCESS'
}